### ISSUE TITLE
Options pour Clementine::dump()

### ISSUE THREAD

**Issue by pawebportage** [pa-de-solminihac/clementine-framework#19]
Ajouter une option pour désactiver la colorisation syntaxique (s'il y a beaucoup de données ça peut être lent à afficher dans le navigateur).

Améliorer l'affichage (stdClass::__set_state passe toujours à la ligne...) : 
```php
       'labels' => array(
        0 => 
        stdClass::__set_state(array(
```

**Comment by pa-de-solminihac** [comment]
obsolète
